apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-chart.name" . }}
  labels: {{- include "helm-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["read"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
